### ISSUE TITLE
Login page (with grid FirstName, LastName and password). Optional redirect of standard login page

### ISSUE THREAD

**Issue by GuduleLapointe** [GuduleLapointe/w4os#9]

**Comment by magicoli** [comment]
Fixed in #971d77439ac5327a73866cbbff08646ba83d3b6b (2.1 stable release)

[gridprofile] shortcode displays now a login form if user is not connected. It can be included in a "Grid Account" page, for example.

Standard login page redirection is not a real priority, as it's possible with existing dedicated plugins.
